//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JOBEntities : DbContext
    {
        public JOBEntities()
            : base("name=JOBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<JobProvider> JobProviders { get; set; }
        public DbSet<JobSeeker> JobSeekers { get; set; }
        public DbSet<JobVacancy> JobVacancies { get; set; }
        public DbSet<Portfolio> Portfolios { get; set; }
    }
}
