//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSeeker
    {
        public JobSeeker()
        {
            this.Portfolios = new HashSet<Portfolio>();
        }
    
        public int Id { get; set; }
        public string Uname { get; set; }
        public string Pass { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Mail { get; set; }
        public string CurrentOccupation { get; set; }
    
        public virtual ICollection<Portfolio> Portfolios { get; set; }
    }
}
