//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobVacancy
    {
        public int Id { get; set; }
        public string JobType { get; set; }
        public string JobDescription { get; set; }
        public string Salary { get; set; }
        public string Address { get; set; }
        public string RequiredSkills { get; set; }
        public string JobLocType { get; set; }
        public int Vacancy { get; set; }
        public int JobProviderId { get; set; }
    
        public virtual JobProvider JobProvider { get; set; }
    }
}
