//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio
    {
        public int Id { get; set; }
        public string Skills { get; set; }
        public string Expertise { get; set; }
        public string Experience { get; set; }
        public string Projects { get; set; }
        public string ExtraCurrActivities { get; set; }
        public int JobSeekerId { get; set; }
    
        public virtual JobSeeker JobSeeker { get; set; }
    }
}
